### ISSUE TITLE
uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)

### ISSUE THREAD

**Issue by sgerrand** [dtao/safe_yaml#80]
I've been getting this error when using `SafeYAML` without `bundle exec`. On a cursory look, it seems like the cause is a reference to `DateTime` without pulling it in from the Ruby standard library. :cold_sweat:  

Backtrace follows:

```
/Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:22:in `<class:Date>': uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:3:in `<class:Parse>'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:2:in `<module:SafeYAML>'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:1:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:14:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:27:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen.rb:42:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:21:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/bin/kitchen:10:in `<top (required)>'
    from /Users/s/.gem/ruby/2.2.3/bin/kitchen:23:in `load'
    from /Users/s/.gem/ruby/2.2.3/bin/kitchen:23:in `<main>'
```

**Comment by javierbertoli** [comment]
As a quick fix, changing [here](https://github.com/dtao/safe_yaml/blob/master/lib/safe_yaml/parse/date.rb#L3-L4)

```ruby
    class Date
        # This one's easy enough :)
```
to

```ruby
    class Date
        require 'time'
        # This one's easy enough :)
```

seems to fix it

**Comment by victort** [comment]
confirmed, @javierbertoli 
that Works For Me™

thanks!

**Comment by y0y0z** [comment]
i was having the same problem when upgrading from ruby version 2.4.2 to 2.5.0
```bash
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468)
$ cat Gemfile.lock | grep -i 'test-kitchen ([0-9]'
    test-kitchen (1.19.2)
```

applying @javierbertoli quick fix resolved my pain.
wonder why i just got this error when the initial issue date it set back to Oct 18, 2015 and @javierbertoli [resolution][1] was not pushed to the upstream or any other suitable fix...

any idea?

[1]: https://github.com/dtao/safe_yaml/issues/80#issuecomment-351776333

**Comment by silverhammermba** [comment]
My only guess is that somebody somewhere was doing a `require 'date'` or `require 'time'` which pulls in the `DateTime` class and this was happening before safe yaml got invoked.

Top level modules are a nasty little bit of global state in Ruby...
